apiVersion: v1
kind: ConfigMap
metadata:
  name: teams-conf
data:
  {{- with .Values.favorite }}
  toppings: |-
    {{- range .Values.devTeams }}
    - {{ . | title | quote }}
    {{- end }}
  {{- end }}


